version: '3'
services:
  was:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=security
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=qwer1234
      - MYSQL_PASSWORD=qwer1234
    volumes:
      - ./mysql:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

volumes:
    mysql:
    redis: